version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    #    environment:
    #      MONGO_INITDB_ROOT_USERNAME: root
    #      MONGO_INITDB_ROOT_PASSWORD: example
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - rom-network
  minio:
    image: minio/minio
    container_name: minio
#    volumes:
#      - data/data
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /tmp/minio
    networks:
      - rom-network
networks:
  rom-network:
    driver: bridge
